credentials:
  usernames:
    nailong@gmail.com: 
      email: "nailong@gmail.com"
      name: "Admin"
      password: "nailong"
cookie:
  expiry_days: 0
  key: "some_signature_key"
  name: "some_cookie_name"